version: '3.9'

services:
  api:
    build: .
    command: npm run dev
    container_name: news-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    container_name: news-mongodb
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  mongo-express:
    image: mongo-express
    container_name: news-me
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=5 --spider http://root:qwerty@mongo-express:8081 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://root:qwerty@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
